### ISSUE TITLE
Last Project Sprint Plans

### ISSUE THREAD

**Issue by tanayp327** [tanayp327/bloggy#14]
# Objective

The aim of this final sprint and feature implementation is to focus on frontend integration. We as a time largely have a coherent backend system with a login and RBAC system, internship system, assignment and grading system, attendance, etc. We need to focus on a frontend system. It is not coherent, there is different themes and styling throughout the pages and there is missing functionality. I will work on the internships system, making sure the page where users can see the information about an internship and confirm the joining process.
---
# Tasks
- [ ] Standardize all features to work with the Person system
- [ ] Fix the themes and redundant links in the navbar, add SASS to internships (all related)
- [ ] Login UI added, set everything up except the storing of roles
- [x] Create inheritance hierarchy for the Person, role saved upon post
- [x] Set up the Entity, Service, Controller, Repository for the Hall Pass Queue
#### Requirements:
- [ ] UI + Theme for all features
- [ ] Person system integration
- [x] Person folder set up
---
#### Theme + Internship
- [ ] Fix existing internship finder replace CSS with Sass, remove the investment swiping
---
#### Person Integration
- [x] Saving roles for the Person
- [ ] Authorization annotations at right endpoints
- [ ] Backend hallpass system change to queue with student objects, change HallPassEntry class
---
## Schedule
- [ ] **Monday**: Talk with Colin about the frontend theme that we decide to use, set up Queue for HallPass, start SASS for Internships
- [ ] **Tuesday**: Finish Sass for Internship, change chatbot and messaging styling, make sure messaging system permissions reflect roles.
- [ ] **Wednesday**: Work on role saving properly so that authorization annotations work.
- [ ] **Thursday**: Add working Person and Roles to other features in the backend
- [ ] **Friday**: Finalize project and test entire project with group
